### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by putraalm** [craxid/GenIXBot#1]
biar ga register dlu buat make nya setting dmna

**Comment by craxid** [comment]
Ganti ke
handler.register = false

**Comment by craxid** [comment]
> biar ga register dlu buat make nya setting dmna

Ubah jadi
```handler.register = false```
di setiap plugin

**Comment by putraalm** [comment]
plugin sebelah mana saya cek gaad gan

**Comment by putraalm** [comment]
disemua plugin bang?
